export const habitaciones = [
    { id: 1, nombre: 'SWB', numero: '101' },
    { id: 2, nombre: 'MAT', numero: '102' },
    { id: 3, nombre: 'DWB', numero: '103' },
    { id: 4, nombre: 'TWB', numero: '104' },
    { id: 5, nombre: 'SUITE', numero: '105' },
    { id: 6, nombre: 'SIMPLE', numero: '106' },
    { id: 7, nombre: 'DOBLE', numero: '107' },
    { id: 8, nombre: 'TWB', numero: '108' },
    { id: 9, nombre: 'TWB', numero: '109' },
    { id: 10, nombre: 'SWB', numero: '110' },
    { id: 11, nombre: 'TWB', numero: '111' },
    { id: 12, nombre: 'DWB', numero: '112' },
    { id: 13, nombre: 'SWB', numero: '113' },
    { id: 14, nombre: 'SIMPLE', numero: '114' },
    { id: 15, nombre: 'TWB', numero: '115' },
];
